# Generated by Django 3.0.5 on 2021-03-07 11:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=64, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Вариант ответа',
                'verbose_name_plural': 'Варианты ответов',
            },
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название опроса')),
                ('start_date', models.DateTimeField(verbose_name='Дата создания')),
                ('end_date', models.DateTimeField(verbose_name='Дата окончания')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Опрос',
                'verbose_name_plural': 'Опросы',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст вопроса')),
                ('question_type', models.CharField(choices=[('Text', 'Ответьте текстом'), ('Choice', 'Выберите один вариант'), ('Multichoice', 'Выберите несколько вариантов')], max_length=11, verbose_name='Тип вопроса')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='polls.Poll', verbose_name='Опрос')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='TextAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='id пользователя')),
                ('text', models.TextField(verbose_name='Текст ответа')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='polls.Question', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Текстовый ответ пользователя',
                'verbose_name_plural': 'Текстовые ответы пользователя',
            },
        ),
        migrations.CreateModel(
            name='MultiChoiceAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='id пользователя')),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Choice')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multi_choice_answer', to='polls.Question')),
            ],
            options={
                'verbose_name': 'Выбор нескольких вариантов',
                'verbose_name_plural': 'Выборы пользователей',
            },
        ),
        migrations.CreateModel(
            name='ChoiceAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='id пользователя')),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='single_choice', to='polls.Choice', verbose_name='Выбор пользователя')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choice_answer', to='polls.Question', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Выбор пользователя',
                'verbose_name_plural': 'Выборы пользователей',
            },
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='polls.Question', verbose_name='Вопрос'),
        ),
        migrations.AddConstraint(
            model_name='textanswer',
            constraint=models.UniqueConstraint(fields=('user_id', 'question'), name='unique_text_answer'),
        ),
        migrations.AddConstraint(
            model_name='multichoiceanswer',
            constraint=models.UniqueConstraint(fields=('user_id', 'choice'), name='unique_multi_choice_answer'),
        ),
        migrations.AddConstraint(
            model_name='choiceanswer',
            constraint=models.UniqueConstraint(fields=('user_id', 'question'), name='unique_choice_answer'),
        ),
    ]
