# Generated by Django 3.0.5 on 2021-03-07 13:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choiceanswer',
            name='user_id',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='id пользователя'),
        ),
        migrations.AlterField(
            model_name='multichoiceanswer',
            name='user_id',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='id пользователя'),
        ),
        migrations.AlterField(
            model_name='textanswer',
            name='user_id',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='id пользователя'),
        ),
    ]
