# Generated by Django 3.0.5 on 2021-03-07 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20210307_1648'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choiceanswer',
            options={'verbose_name': 'Выбор пользователя', 'verbose_name_plural': 'Выбор одного варианта'},
        ),
        migrations.AlterModelOptions(
            name='multichoiceanswer',
            options={'verbose_name': 'Выбор нескольких вариантов', 'verbose_name_plural': 'Выбор нескольких пользователей'},
        ),
    ]
