# Generated by Django 3.0.5 on 2021-03-05 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20210305_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='start_date',
            field=models.DateTimeField(verbose_name='Дата создания'),
        ),
    ]
