# Generated by Django 3.0.5 on 2021-03-08 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20210307_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multichoiceanswer',
            name='choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multi_choices', to='polls.Choice'),
        ),
    ]
