# Generated by Django 3.0.5 on 2021-03-06 02:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20210306_0157'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name=django.core.validators.MinValueValidator(1))),
                ('text', models.TextField(verbose_name='Текст ответа')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='polls.Question')),
            ],
            options={
                'verbose_name': 'Текстовый ответ пользователя',
                'verbose_name_plural': 'Текстовые ответы пользователя',
            },
        ),
        migrations.CreateModel(
            name='MultiChoiceAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Choice')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multi_choice_answer', to='polls.Question')),
            ],
        ),
        migrations.CreateModel(
            name='ChoiceAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name=django.core.validators.MinValueValidator(1))),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Choice')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choice_answer', to='polls.Question')),
            ],
            options={
                'verbose_name': 'Выбор пользователя',
                'verbose_name_plural': 'Выборы пользователя',
            },
        ),
        migrations.AddConstraint(
            model_name='textanswer',
            constraint=models.UniqueConstraint(fields=('user_id', 'question'), name='unique_text_answer'),
        ),
        migrations.AddConstraint(
            model_name='multichoiceanswer',
            constraint=models.UniqueConstraint(fields=('user_id', 'choice'), name='unique_multu_choice_answer'),
        ),
        migrations.AddConstraint(
            model_name='choiceanswer',
            constraint=models.UniqueConstraint(fields=('user_id', 'question'), name='unique_choice_answer'),
        ),
    ]
