# Generated by Django 3.0.5 on 2021-03-06 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20210306_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='active',
        ),
    ]
